import { CiHeart } from "react-icons/ci";
import {Profile1 } from '/public/images/image1.png'

export const data = [
  {
    id: 1,
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    id: 2,
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    id: 3,
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    id: 4,
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    id: 5,
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    id: 6,
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    id: 7,
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    id: 8,
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
  {
    img: { Profile1 },
    title: "Imani",
    desc: "Long gown light coffee dress",
    icon: <CiHeart className="icon-love" />,
    price: 150,
  },
];
